name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: wst24365888
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: large
          config_timezone: Asia/Taipei
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: html, css, javascript, c#, shaderlab
          plugin_languages_limit: 20
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_skipped: bert-named-entity-recognition, teacher-qualifying-exam-sign-up-system, utf8-converter, nctu-gameweek
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 100
          plugin_lines_repositories_limit: 100
          plugin_lines_sections: base
          repositories_affiliations: OWNER, ORGANIZATION_MEMBER, COLLABORATOR
          repositories_batch: 1000